FROM node:lts-alpine3.17 AS build

RUN adduser -D appuser

WORKDIR /usr/frontend

RUN chown -R appuser:appuser /usr/frontend

ENV PATH /usr/frontend/node_modules/.bin:$PATH

COPY --chown=appuser:appuser package*.json ./

USER appuser

RUN npm install

COPY --chown=appuser:appuser ./ ./

RUN npm run build

FROM nginx:1.23.3-alpine

ENV PATH /usr/frontend/node_modules/.bin:$PATH

#RUN rm -rf ./*

#RUN addgroup -S nginx && adduser -S -G nginx nginx

RUN touch /var/run/nginx.pid

WORKDIR /usr/share/nginx/html

COPY --chown=nginx:nginx nginx.conf /etc/nginx/nginx.conf

COPY --from=build --chown=nginx:nginx /usr/frontend/build ./

RUN chown -R nginx:nginx /var/run/nginx.pid /var/cache/nginx /var/run /var/log/nginx /etc/nginx/nginx.conf

RUN chmod -R g+w /var/run/nginx.pid /var/cache/nginx /var/run /var/log/nginx /etc/nginx/nginx.conf

USER nginx

EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]
