version: '3.8'

services:
  backend:
    build: ./backend/
    ports:
      - 8000:8000
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_HOST=postgresdb
    volumes:
      - ./backend:/backend:ro
    depends_on:
      - postgresdb

  postgresdb:
    container_name: postgres_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USR=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  frontend:
    build: ./frontend/
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend:ro

