version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_HOST=mysqldb
    volumes:
      - ./backend/data:/var/lib/postgresql/data:ro
    depends_on:
      - mysqldb

  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    restart: always
    ports:
      - 3307:3307
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./frontend/:/usr/share/nginx/html:ro
    stdin_open: true
    tty: true

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081

