version: "3"

services:
  database:
    image: postgres:15.2-alpine
    container_name: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - db.env
  backend:
    build:
      context: ./backend
      args:
        - ENVIRONMENT=tst
    ports:
      - '8000:8000'
    entrypoint: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000" ]
    volumes:
      - ./backend/:/pyroot/backend
      - data:/pyroot/backend/data
    env_file:
      - ./env
    depends_on:
      - database
  #backend-tests:
  #  build: ./backend
  #  volumes: ./backend:/pyroot/backend
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend/:/usr/share/nginx/html/

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./backend/data
