version: "3.8"

services:
  database:
    image: postgres:15.2-alpine
    container_name: 'postgres'
    ports:
      - '5433:5432'
    volumes:
      - ./backend/data:/var/lib/postgresql/data
    env_file:
      - ./backend/db.env
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    #entrypoint: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000" ]
    volumes:
      - ./backend/:/pyroot/backend
      - ./backend/data:/pyroot/backend/data
    env_file:
      - ./backend/.env
    depends_on:
      - database
    networks:
      - my-app
  #backend-tests:
  #  build: ./backend
  #  volumes: ./backend:/pyroot/backend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./frontend/:/usr/share/nginx/html/
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - my-app

networks:
  my-app:
